### ISSUE TITLE
Fix CRAN errors

### ISSUE THREAD

**Issue by goergen95** [mapme-initiative/mapme.biodiversity#368] opened 2024-08-29 06:27 UTC
We see:

```r

    ── Error ('test-calc_gsw_time_series.R:9:3'): calc_gsw_time_series works ───────
    Error in `.probe_dsn(outdir)`: Destination '/home/hornik/tmp/R.check/r-devel-gcc/Work/build/Packages/mapme.biodiversity/res' is not writeable via GDAL.
    Backtrace:
        ▆
     1. └─mapme.biodiversity::mapme_options(outdir = outdir, verbose = FALSE) at test-calc_gsw_time_series.R:9:3
     2.   └─mapme.biodiversity:::.probe_dsn(outdir)
    ── Error ('test-get_gsw_time_series.R:9:3'): get_gsw_time_series works ─────────
    Error in `.probe_dsn(outdir)`: Destination '/home/hornik/tmp/R.check/r-devel-gcc/Work/build/Packages/mapme.biodiversity/res' is not writeable via GDAL.
    Backtrace:
        ▆
     1. └─mapme.biodiversity::mapme_options(outdir = outdir, verbose = FALSE) at test-get_gsw_time_series.R:9:3
     2.   └─mapme.biodiversity:::.probe_dsn(outdir)

```

and a fix before 2024-09-11.

**Comment by karpfen** [comment] 2024-08-30 08:32
The issue is now fixed, keeping this on hold until the CRAN checks go through.

**Closed** 2024-09-02 09:35 UTC
