### ISSUE TITLE
Rename resources and indicators

### ISSUE THREAD

**Issue by Ohm-Np** [mapme-initiative/mapme.biodiversity#68] opened 2022-05-13 12:20 UTC
![Screenshot 2022-05-13 141648](https://user-images.githubusercontent.com/56826085/168281577-bae92d99-ef4e-439c-8403-2542a2c77590.jpg)

Johannes suggests renaming some resources and indicators in order to increase consistency and facilitate the usage of the packge. The goal should be that the user is able to understand which indicators are available and what they mean when typing `names(available_indicators())` **without having to look up the documentation** . The same should apply when typing in `names(available_ressources())`. 

Below is a complete list of all indicators including changes that Johannes suggests. 

|resources|indicators|changes_required|
|---|---|---|
|chirps|precipitation_chirps|yes|
|esa|landcover|no|
|gmw|mangroves_area|yes|
|gfw_treecover|treecover_area</br>treecoverloss_area</br>treecover2000_area|yes|
|gfw_emissions|treecoverloss_emissions|yes|
|nelson_et_al|traveltime|yes (formerly called accessibility without ressource)|
|nasa_srtm|elevation</br>TRI|yes|
|nasa_grace|drought_indicator|yes|
|soilgrid|soilproperties|no|
|teow|ecoregion</br>biome|yes|
|worldclim_precipitation|precipitation|yes|
|worldclim_temperature|temperature_max_wc</br>temperature_min_wc|yes|
|worldpop|population_count|yes|

**Comment by Jo-Schie** [comment] 2022-05-14 08:14
fyi @goergen95 . 

@Ohm-Np : I guess the easiest way to implement this would be to parse the names in the scripts and then eventually substitute it automatically, if possible. At least that would avoid that you forget anything. It requires, however, being very cautious when programming the regex.

**Comment by goergen95** [comment] 2022-05-14 10:41
While you are doing this it would be a good idea to revise the roxygen documentation of both resources and indicators to harmonize the names we are using. I guess a little bit of manual work will be involved...

**Comment by Ohm-Np** [comment] 2022-05-19 17:39
- [ ] chirps
- [ ] mangrove
- [ ] accessibility
- [ ] srtm
- [ ] drought_indicator
- [ ] teow
- [ ] worldclim
- [ ] worldpop
- [ ] gfw

**Comment by Ohm-Np** [comment] 2022-05-20 13:11
I rather found renaming/replacing every `words` quite easier although it demands more cautiousness. 
Here's my checklist while working on the renaming part:

- resource backlog
- get_resource
- inst/res 
- indicator backlog
- calc_indicator
- testhat

In case of `worldclim` - since we have three different resources (i.e. min/max temperature, and precipitation) which needs to be called specifically to download them - it would be quite confusing if we call these resources by only one name 'worldclim'. 
So, I think the `one-to-many` naming approach in resources might not be a good idea. Same applies for `gfw` too.

**Comment by Jo-Schie** [comment] 2022-05-20 13:43
> I rather found renaming/replacing every `words` quite easier although it demands more cautiousness. Here's my checklist while working on the renaming part:
> 
> * resource backlog
> * get_resource
> * inst/res
> * indicator backlog
> * calc_indicator
> * testhat
> 
> In case of `worldclim` - since we have three different resources (i.e. min/max temperature, and precipitation) which needs to be called specifically to download them - it would be quite confusing if we call these resources by only one name 'worldclim'. So, I think the `one-to-many` naming approach in resources might not be a good idea. Same applies for `gfw` too.

okay that makes sense. I edit the table above to avoid `one-to-many`. please see my edits above.

**Comment by Ohm-Np** [comment] 2022-05-27 12:14
I just completed renaming all resources and indicators and pushed all the changes to the branch named _rename_resources-indicators_. However, I am getting this warning everytime while performing devtools::check() 
`WARNING
  ‘qpdf’ is needed for checks on size reduction of PDFs`
How did you manage to get rid of this @goergen95 ?

Except this, everything seems to work fine (all 180 tests). Should I open PR now or is it okay to keep the changes only in this branch @Jo-Schie ?

**Comment by goergen95** [comment] 2022-05-28 09:56
Thanks a lot for the changes!
You could install the package via `install.packages("qpdf")` to get rid of this note. However, could you also consider updating your R version? You seem to use an R version 3.x. With versions below 4.x character columns are automatically read as factors. This will lead to test failures because we use more recent versions of R with GitHub Actions.

Some minor comments on the proposed naming scheme:
- precipitation naming scheme is not consistent, I think it should be `precipitation_chirps` and `precipitation_wc`
- I would suggest to use lower cases for `tri` that is more in line with all other indicators
- the function `.calc_dem` should then be renamed to `.calc_elevation`?
- there is a misunderstanding in relation to the GFW indicators. The one currently framed `treecover_area` returns the respective area covered by trees, the one framed `treecoverloss_emissions` just returns the amount of GHG caused by treecover loss while the one framed `treecoverloss_area` actually returns both of the previous indicators (treecover area + GHG emissions) thus the last name is misleading

**Comment by Ohm-Np** [comment] 2022-05-29 10:24
Hi @goergen95, thanks for the suggestions. I have still some queries:
> could you also consider updating your R version?

I am using the Rserver. Should I use desktop version, there I can update my Rstudio version to the latest one. But, it's windows and windows should not be the problem right?

> With versions below 4.x character columns are automatically read as factors.

Ah okay, that's why during devtools test, it asks everytime to accept the new snapshot changes. 

> precipitation naming scheme is not consistent, I think it should be precipitation_chirps and precipitation_wc

Or, `precipitation_worldclim` ?

> thus the last name `treecoverloss_area` is misleading

Would you suggest me new name for this indicator which resonates with the other indicators as well?

**Comment by goergen95** [comment] 2022-05-30 03:25
Could be worth updating the container. @Jo-Schie what do you think?

Agreed, `precipitation_worldclim` sounds reasonable. 

Not so sure what makes sense with the treecover variables, though. How about `treecover_area`, `treecover_emissions` and `treecover`?

**Comment by Jo-Schie** [comment] 2022-05-30 11:07
Hi @goergen95 and @Ohm-Np . I agree on the renaming suggestions. Nevertheless I'm unsure as to why we need the functionality to calculate both indicators (area and emission) with one single command if we also provide them to the user with a combined argument. My suggestion would be to delete or deactivate the combined function or is it related to performance increase? If so, then my suggestion would be to name it `treecover_area_and_emissions`. Not a very beautifull name but clearer to the enduser on what to expect without having to go in depth through the documentation. 

As to updating R on the server. I just read [this threat](treecoverloss_area) about updating R on the server and it suggests to use multiple R versions side by side because updating to the newest version potentially crashes old scripts and libraries would need to be re-installed. I would prefer not to do this at the moment. Is there a workaround? Otherwise I would have to speak to the admins first and ask for help.

**Comment by Ohm-Np** [comment] 2022-05-31 19:12
Just updated the names as following
- `tri`
- `calc_elevation`
- `precipitation_wc`
- `treecover_area_and_emissions`

However, the warning with `qpdf` persists even after installing the package, and the snapshots have been changed.

**Comment by Ohm-Np** [comment] 2022-07-20 09:31
Hi @goergen95, 

I tested the package from this branch with Ubuntu 22.04 from R4.2.1 and also merged the latest changes from main to this branch.   
While testing from this Ubuntu system, both devtools tests and checks pass, yet for some reason, the tests are failing in CI.

**Closed** 2022-08-01 18:51 UTC
Labels: enhancement
